//some improvements can be made here for edge cases
//Sourced from https://www.peta.org with additions by myself
//to improve the reliability
const animalFreeList = [
  "Adrenaline",
  "Alanine",
  "Albumen",
  "Albumin",
  "Alcloxa",
  "Aldioxa",
  "Aliphatic Alcohol",
  "Allantoin",
  "Alligator Skin",
  "Alpha-Hydroxy Acids",
  "Ambergris",
  "Amino Acids",
  "Aminosuccinate Acid",
  "Angora",
  "Animal Fats and Oils",
  "Animal Hair",
  "Arachidonic Acid",
  "Arachidyl Proprionate",
  "Beef",
  "Bee Pollen",
  "Bee Products",
  "Beeswax. Honeycomb",
  "Biotin. Vitamin H. Vitamin B Factor",
  "Blood",
  "Boar Bristles",
  "Bone Char",
  "Bone Meal",
  "Calciferol",
  "Calfskin",
  "Caprylamine Oxide",
  "Capryl Betaine",
  "Caprylic Acid",
  "Caprylic Triglyceride",
  "Carbamide",
  "Carmine. Cochineal. Carminic Acid",
  "Carminic Acid",
  "Carotene. Provitamin A. Beta Carotene",
  "Casein. Caseinate. Sodium Caseinate",
  "Caseinate",
  "Cashmere",
  "Castor. Castoreum",
  "Castoreum",
  "Catgut",
  "Cera Flava",
  "Cerebrosides",
  "Cetyl Alcohol",
  "Cetyl Palmitate",
  "Cheese",
  "Chicken",
  "Chitosan",
  "Cholesterin",
  "Cholesterol",
  "Choline Bitartrate",
  "Civet",
  "Cochineal",
  "Cod Liver Oil",
  "Collagen",
  "Colors. Dyes",
  "Corticosteroid",
  "Cortisone. Corticosteroid",
  "Cysteine, L-Form",
  "Cystine",
  "Dexpanthenol",
  "Diglycerides",
  "Dimethyl Stearamine",
  "Down",
  "Duodenum Substances",
  "Dyes",
  "Egg",
  "Eggs",
  "Egg Protein",
  "Elastin",
  "Emu Oil",
  "Ergocalciferol",
  "Ergosterol",
  "Estradiol",
  "Estrogen. Estradiol",
  "Fats",
  "Fatty Acids",
  "FD&C Colors",
  "Feathers",
  "Fish Liver Oil",
  "Fish Oil",
  "Fish Scales",
  "Fur",
  "Gel",
  "Gelatin. Gel",
  "Glucose Tyrosinase",
  "Glycerides",
  "Glycerin. Glycerol",
  "Glycerol",
  "Glyceryls",
  "Glycreth-26",
  "Guanine. Pearl Essence",
  "Hide Glue",
  "Honey",
  "Honeycomb",
  "Horsehair",
  "Hyaluronic Acid",
  "Hydrocortisone",
  "Hydrolyzed Animal Protein",
  "Imidazolidinyl Urea",
  "Insulin",
  "Isinglass",
  "Isopropyl Lanolate",
  "Isopropyl Myristate",
  "Isopropyl Palmitate",
  "Keratin",
  "Lactic Acid",
  "Lactose",
  "Laneth",
  "Lanogene",
  "Lanolin. Lanolin Acids. Wool Fat. Wool Wax",
  "Lanolin Alcohol",
  "Lanosterols",
  "Lard",
  "Leather",
  "Suede",
  "Calfskin",
  "Sheepskin",
  "Alligator Skin",
  "Lamb",
  "Lecithin. Choline Bitartrate",
  "Linoleic Acid",
  "Lipase",
  "Lipids",
  "Lipoids. Lipids",
  "Marine Oil",
  "Methionine",
  "Milk Protein",
  "Mink Oil",
  "Monoglycerides. Glycerides.",
  "Musk (Oil)",
  "Myristal Ether Sulfate",
  "Myristic Acid",
  "Myristyls",
  "“Natural Sources.",
  "Nucleic Acids",
  "Ocenol",
  "Octyl Dodecanol",
  "Oleic Acid",
  "Oils",
  "Oleths",
  "Oleyl Alcohol. Ocenol",
  "Oleyl Arachidate",
  "Oleyl Imidazoline",
  "Oleyl Myristate",
  "Oleyl Oleate",
  "Oleyl Stearate",
  "Palmitamide",
  "Palmitamine",
  "Palmitate",
  "Palmitic Acid",
  "Panthenol",
  "Dexpanthenol",
  "Vitamin B-Complex Factor",
  "Provitamin B-5",
  "Panthenyl",
  "Pepsin",
  "Placenta",
  "Placenta Polypeptides Protein",
  "Afterbirth",
  "Polyglycerol",
  "Polypeptides",
  "Polysorbates",
  "Pork",
  "Pristane",
  "Progesterone",
  "Propolis",
  "Provitamin A",
  "Provitamin B-5",
  "Provitamin D-2",
  "Rennet. Rennin",
  "Rennin",
  "Resinous Glaze",
  "Retinol",
  "Ribonucleic Acid",
  "RNA. Ribonucleic Acid",
  "Royal Jelly",
  "Sable Brushes",
  "Sea Turtle Oil",
  "Shark Liver Oil",
  "Sheepskin",
  "Shellac. Resinous Glaze",
  "Silk. Silk Powder",
  "Snails",
  "Sodium Caseinate",
  "Sodium Steroyl Lactylate",
  "Sodium Tallowate",
  "Spermaceti",
  "Cetyl Palmitate",
  "Sperm Oil",
  "Sponge (Luna and Sea)",
  "Squalane",
  "Squalene",
  "Stearamide",
  "Stearamine",
  "Stearamine Oxide",
  "Stearates",
  "Stearic Acid",
  "Stearic Hydrazide",
  "Stearone",
  "Stearoxytrimethylsilane",
  "Stearoyl Lactylic Acid",
  "Stearyl Acetate",
  "Stearyl Alcohol. Sterols",
  "Stearyl Betaine",
  "Stearyl Caprylate",
  "Stearyl Citrate",
  "Stearyldimethyl Amine",
  "Stearyl Glycyrrhetinate",
  "Stearyl Heptanoate",
  "Stearyl Imidazoline",
  "Stearyl Octanoate",
  "Stearyl Stearate",
  "Steroids. Sterols",
  "Sterols",
  "Suede",
  "Tallow",
  "Tallow Fatty Alcohol",
  "Stearic Acid",
  "Tallow Acid",
  "Tallow Amide",
  "Tallow Amine",
  "Talloweth-6",
  "Tallow Glycerides",
  "Tallow Imidazoline",
  "Triterpene Alcohols",
  "Turtle Oil. Sea Turtle Oil",
  "Tyrosine",
  "Urea. Carbamide",
  "Uric Acid",
  "Vitamin A",
  "Vitamin B-Complex Factor",
  "Vitamin B Factor",
  "Vitamin B12",
  "Vitamin D",
  "Ergocalciferol",
  "Vitamin D2",
  "Ergosterol",
  "Provitamin D2",
  "Calciferol",
  "Vitamin D3",
  "Vitamin H",
  "Wax",
  "Whey",
  "Wool",
  "Wool Fat",
  "Wool Wax"]

//This function will run through any list and check it
//against the list of ingredients above
//room for serious improvement for speed as well as ability
//to return which ingredients are not vegan
export function veganIngredients(ingredients){
  let upperCaseList = animalFreeList.map(value => {
      return value.toUpperCase();
    });
  return upperCaseList.every(i => {
    return ingredients.toUpperCase().indexOf(i) === -1
  })
}


//Function checks the specific label list given back by
//Edamans 'heathLabels'
export function isVegan (labels, ingr){
    if (labels.indexOf('VEGAN') !== -1){
      return true
    }
    if (ingr){
      console.log('no label checking ingredients ',veganIngredients(ingr))
      return veganIngredients(ingr)
    }
    return false
  }

export function toTitleCase(str) {
    return str.replace(/_/g, ' ').replace(/\w\S*/g, function(txt){return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();});
}

export function cleanString(input) {
    var output = "";
    for (var i=0; i<input.length; i++) {
        if (input.charCodeAt(i) <= 127) {
            output += input.charAt(i);
        }
    }
    return output;
}
